<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
  </ItemGroup>

	<ItemGroup>
		<!-- Prevents local data from wiping the live server database -->
		<Content Update="taskHistory.json" CopyToPublishDirectory="Never" />
		<Content Update="users.json" CopyToPublishDirectory="Never" />

		<!-- Keeps your local passwords off the server -->
		<Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
	</ItemGroup>
	
</Project>
